fractal-analytics-platform/fractal-server

- alembic.ini
- fractal_server/migrations/env.py
- poetry.lock
- scripts/testserver.py
> change uvicorn.run path and import path

- poetry.lock
- pyproject.toml
This PR should at least mitigate #3, and be a good starting point for then switching to parsl `1.3.0` once it's released.
> Use parsl 1.3.0dev1 (ref #23)

- .github/workflows/ci.yml
> Include python 3.9 for github CI

- .gitignore
- fractal_server/app/runner/__init__.py
- fractal_server/app/runner/runner_utils.py
- fractal_server/config.py
- tests/test_apply_worfklow.py
> Parsl executors

- fractal_server/__main__.py
- pyproject.toml
- scripts/client.py
- scripts/testserver.py
> use __main__ for starting a test server

- fractal_server/__main__.py
> select port when launching fractal-server

- fractal_server/app/runner/runner_utils.py
> Add PARSL_CONFIG=fmi option

- poetry.lock
- pyproject.toml
- tests/test_apply_worfklow.py
- tests/test_full_workflow.py
> Fix tests after task updates

- fractal_server/__init__.py
- fractal_server/config.py
- pyproject.toml
> Move __VERSION__ to __init__.py [closes #50]

- fractal_server/app/api/v1/task.py
> Better failure when task name already exists (closes #64)

- fractal_server/app/api/v1/task.py
> dev to main (better failure handling for duplicate task)

- fractal_server/__main__.py
- fractal_server/app/api/v1/task.py
> Fix port type=int in argparse

- fractal_server/app/models/task.py
- poetry.lock
- tests/test_full_workflow.py
> Update Subtask to allow multiple identical subtasks

- fractal_server/__main__.py
- fractal_server/app/api/v1/project.py
- fractal_server/app/runner/__init__.py
- fractal_server/app/runner/runner_utils.py
- tests/fixtures_server.py
- tests/test_apply_worfklow.py
- tests/test_full_workflow.py
A dedicated Parsl DataFlowKernel (DFK) is created for each workflow.
The task factory is refactored to set explicitly the DFK the app it creates belongs to.
close #83, #3
> Dfk runners

- fractal_server/app/runner/runner_utils.py
Closes https://github.com/fractal-analytics-platform/fractal-server/issues/34
> Update slurm settings for FMI

- fractal_server/app/runner/runner_utils.py
> Remove duplicate LocalChannel from SlurmProvider (closes #99)

- tests/test_db_models.py
> db updates

- .gitignore
- fractal_server/app/api/v1/project.py
- fractal_server/app/models/models_utils.py
- fractal_server/app/models/task.py
- fractal_server/app/runner/__init__.py
- fractal_server/app/runner/runner_utils.py
- fractal_server/config.py
- fractal_server/config_runner.py
- fractal_server/utils.py
- poetry.lock
- pyproject.toml
- tests/test_apply_worfklow.py
closes fractal-analytics-platform/fractal-server#10
closes fractal-analytics-platform/fractal-server#111
closes #115 
Refs:
* fractal-analytics-platform/fractal-server#2
* fractal-analytics-platform/fractal-server#70
* fractal-analytics-platform/fractal#289 
* fractal-analytics-platform/fractal-server#114
> Server updates to submit as sudo + other things

- fractal_server/app/api/v1/project.py
- fractal_server/app/api/v1/task.py
- fractal_server/app/models/run.py
- fractal_server/app/runner/__init__.py
- fractal_server/utils.py
- poetry.lock
- pyproject.toml
- tests/test_apply_worfklow.py
- tests/test_full_workflow.py
- tests/test_unit_utils.py
> create job table

- poetry.lock
- pyproject.toml
> Use parsl fork

- fractal_server/app/models/__init__.py
> Fix db error

- fractal_server/app/runner/runner_utils.py
> Allow LocalProvider execution (despite SLURM username being set)

- fractal_server/app/runner/runner_utils.py
>  Allow LocalProvider execution (despite SLURM username being set) / second part

- fractal_server/app/models/models_utils.py
- fractal_server/app/models/run.py
- fractal_server/utils.py
- tests/test_unit_utils.py
> Move get_timestamp to models_utils (close #144)

- .github/workflows/project-management.yml
See https://github.com/fractal-analytics-platform/fractal-demos/issues/12
> Automation to automatically add issues to project board

- fractal_server/app/runner/runner_utils.py
- fractal_server/config_runner.py
> Switch off parsl monitoring (close #148)

- fractal_server/app/api/__init__.py
- fractal_server/app/api/v1/workflow.py
- fractal_server/app/models/__init__.py
- fractal_server/app/models/workflow.py
- fractal_server/app/schemas/__init__.py
- fractal_server/app/schemas/task.py
- tests/test_workflow_api.py
> workflow api POST

- fractal_server/app/models/project.py
- fractal_server/app/models/workflow.py
- tests/test_unit_db_models.py
- tests/test_unit_utils.py
> unit tests for cascade on delete

- fractal_server/app/api/v1/project.py
- fractal_server/app/api/v1/workflow.py
- fractal_server/app/models/workflow.py
- fractal_server/app/schemas/workflow.py
- tests/test_process_runner.py
- tests/test_unit_db_models.py
> Structure of the Workflow API

- fractal_server/app/schemas/manifest.py
also add documentation
ref #195
> make meta optional

- fractal_server/app/api/v1/task.py
- fractal_server/app/db/__init__.py
- fractal_server/app/schemas/task.py
- fractal_server/migrations/env.py
- fractal_server/tasks/collection.py
- tests/fixtures_server.py
- tests/test_task_api.py
- tests/test_task_collection_pypi.py
- collect tasks in the background
- check installation status
> 204 task collection in the background

- fractal_server/tasks/collection.py
- fractal_server/utils.py
- tests/test_task_api.py
- tests/test_task_collection_pypi.py
> write full output/error to logger

- tests/data/fractal-tasks-dummy/pyproject.toml
> add pydantic dependency

- fractal_server/app/models/task.py
- fractal_server/app/models/workflow.py
- fractal_server/app/schemas/manifest.py
- fractal_server/app/schemas/task.py
- fractal_server/tasks/__FRACTAL_MANIFEST__.json
- fractal_server/utils.py
- tests/test_backend_parsl_executors.py
- tests/test_backend_runners.py
> Move `executor` and `parallelization_level` to `task.meta`

- fractal_server/app/api/v1/workflow.py
- fractal_server/app/schemas/workflow.py
- tests/test_workflow_api.py
> 231 patch workflowtask

- fractal_server/app/runner/_common.py
- fractal_server/tasks/dummy.py
- fractal_server/tasks/dummy_parallel.py
- tests/test_backend_parsl_executors.py
- tests/test_backend_process.py
- tests/test_backend_runners.py
- tests/test_full_workflow.py
- tests/test_unit_dummytasks.py
> Sanitize component to build JSON-file names

- fractal_server/app/models/__init__.py
- fractal_server/app/models/run.py
- fractal_server/app/models/state.py
- tests/test_unit_db_models.py
> add arbitrary data table

- fractal_server/app/models/workflow.py
- fractal_server/app/runner/_common.py
- fractal_server/app/runner/_slurm/__init__.py
- fractal_server/app/runner/_slurm/executor.py
- fractal_server/config.py
- tests/fixtures_server.py
- tests/fixtures_slurm.py
- tests/fixtures_tasks.py
- tests/test_backend_slurm.py
> 278 set clusterfutures slurm options

- fractal_server/app/runner/_slurm/executor.py
- tests/fixtures_slurm.py
- tests/test_backend_slurm.py
> consistently pass commands as list of strings

- tests/fixtures_server.py
- tests/test_fixtures_settings_factory.py
> make a new copy of the settings object

- .github/workflows/ci.yml
- fractal_server/app/runner/_parsl/__init__.py
- fractal_server/app/runner/_parsl/_setup.py
- fractal_server/config.py
- poetry.lock
- pyproject.toml
- tests/test_full_workflow.py
> Handle parsl dependency/backend

- fractal_server/app/api/v1/job.py
- fractal_server/app/runner/_common.py
* the full dataset metdata is written to `metadata.json` after each task
* the `history` key is read from the metadata file and added to the payload of the monitoring endpoint
> provide history in monitoring endpoint

- fractal_server/app/runner/_slurm/__init__.py
- fractal_server/app/runner/_slurm/executor.py
- tests/test_backend_slurm.py
> Fix SLURM config

- fractal_server/app/api/v1/task.py
- tests/test_task_api.py
> Correctly enforce check that state_id exists

- fractal_server/app/api/v1/job.py
- fractal_server/app/api/v1/project.py
- tests/fixtures_server.py
- tests/test_project.py
> New monitoring endpoint: list all jobs

- fractal_server/app/api/v1/job.py
- tests/fixtures_server.py
- tests/test_full_workflow.py
- tests/test_project.py
> add download logs endpoint

- fractal_server/app/runner/__init__.py
- fractal_server/app/runner/_common.py
- fractal_server/tasks/dummy.py
- fractal_server/tasks/dummy_parallel.py
> More verbose logging

- fractal_server/app/api/v1/dataset.py
- fractal_server/app/api/v1/project.py
- fractal_server/app/api/v1/security.py
- fractal_server/app/api/v1/task.py
- fractal_server/app/api/v1/workflow.py
> Add type hints to endpoints

- fractal_server/app/api/v1/project.py
- fractal_server/app/api/v1/task.py
- fractal_server/app/api/v1/workflow.py
- fractal_server/app/runner/common.py
- fractal_server/tasks/collection.py
- scripts/mypy-scan
Let's run the mypy-scan script a few times, and possibly solve some glitches here and there
> mypy-based updates

- tests/data/slurm_docker_images/master/Dockerfile
- tests/data/slurm_docker_images/master/sudoers
- tests/fixtures_slurm.py
> use fractal user to execute the slurm commands

- fractal_server/app/runner/_common.py
- fractal_server/app/runner/_slurm/executor.py
- fractal_server/app/runner/_slurm/remote.py
- fractal_server/app/runner/common.py
- fractal_server/config.py
- tests/fixtures_server.py
> Fix unexpected JobExecutionError

- fractal_server/config.py
- fractal_server/main.py
> expose admin user and password as variables

- docs/users.md
- fractal_server/main.py
Fix a trivial bug (wrong env-variable name), and include a docs-update commit that somehow was not pushed.
> Bugfix for env variable name

- CHANGELOG.md
- fractal_server/app/runner/_common.py
- fractal_server/config.py
- fractal_server/tasks/dummy_parallel.py
- tests/test_backend_local.py
- tests/test_backend_runners.py
- tests/test_unit_settings.py
> Introduce maximum number of simultaneously-running parallel tasks per workflow

- fractal_server/app/api/v1/task.py
- fractal_server/app/security/__init__.py
- tests/test_task_api.py
> task_update endpoint partially fixed

- CHANGELOG.md
- fractal_server/config.py
- tests/data/example_server_startup/.gitignore
- tests/data/example_server_startup/README.md
- tests/data/example_server_startup/startup.sh
I added checks for:
* missing sbatch/squeue commands (for slurm backend)
* missing slurm-config file (for slurm backend)
Those were the ones I had in mind.
Unless @mfranzon has other suggestions, let's merge this PR and re-open the #476 issue (or a new one) when we hit other errors downstream that are due to some "wrong" configuration and could be caught at startup.
> Improve check_settings (ref #476)

- CHANGELOG.md
- fractal_server/app/runner/_slurm/executor.py
- fractal_server/app/runner/_slurm/remote.py
> Check version match in slurm remote worker (ref #375)

- CHANGELOG.md
- fractal_server/app/api/v1/project.py
- tests/test_project_api.py
> Handle wrong payload if `create_project`

- CHANGELOG.md
- fractal_server/app/runner/_slurm/executor.py
- fractal_server/app/runner/common.py
- tests/test_full_workflow.py
> Fix duplicate TaskExecutionError logs in slurm backend

- CHANGELOG.md
- fractal_server/app/api/v1/workflow.py
- tests/test_workflow_api.py
> Add 'order' to patch_workflow_task

- CHANGELOG.md
- poetry.lock
- pyproject.toml
Address starlette-related security warning by dependabot
> Bump up fastapi version from 0.89 to 0.95

- fractal_server/app/api/v1/project.py
> use `_get_dataset_check_owner`

- fractal_server/app/runner/_slurm/_batching.py
- fractal_server/app/runner/_slurm/_slurm_config.py
- fractal_server/app/runner/_slurm/executor.py
- tests/test_unit_slurm_batching.py
- tests/test_unit_slurm_config.py
> Rename SLURM-batching variables

- CHANGELOG.md
- docs/internals/logs.md
- fractal_server/app/runner/_slurm/_slurm_config.py
- fractal_server/app/runner/_slurm/_subprocess_run_as_user.py
- fractal_server/app/runner/_slurm/executor.py
- fractal_server/logger.py
Here we shall include more detailed logs, to further debug #615
> Increase (DEBUG) logging verbosity, to address SLURM overheads #615

- CHANGELOG.md
- docs/internals/runners/slurm.md
- fractal_server/app/runner/__init__.py
- fractal_server/app/runner/_local/__init__.py
- fractal_server/app/runner/_slurm/__init__.py
- fractal_server/app/runner/_slurm/_slurm_config.py
- fractal_server/app/runner/_slurm/executor.py
- tests/test_unit_slurm_config.py
> Expose local user's exports in SLURM configuration file

- CHANGELOG.md
- fractal_server/app/runner/_slurm/__init__.py
- fractal_server/app/runner/_slurm/_slurm_config.py
- tests/test_unit_slurm_config.py
> Bugfix for user_local_export

- .github/workflows/ci.yml
- CHANGELOG.md
- fractal_server/app/api/v1/task.py
- fractal_server/tasks/collection.py
- tests/test_task_api.py
* Close #670
* Close #672 (ref https://github.com/fractal-analytics-platform/fractal-common/issues/25)
To do
> Include extras for local-package collection (close #670)

- fractal_server/app/api/v1/project.py
- fractal_server/app/runner/__init__.py
- fractal_server/app/runner/common.py
> Make output_dataset_id a required argument of apply-workflow endpoint

- fractal_server/app/api/v1/project.py
- fractal_server/app/models/workflow.py
- fractal_server/app/runner/common.py
- tests/test_project_api.py
> Review use of output_dataset in apply-workflow endpoint

- tests/test_common.py
- tests/test_dataset_api.py
- tests/test_task_api.py
> Improve coverage

- fractal_server/config.py
- fractal_server/main.py
> More flexible allow origins

- CHANGELOG.md
- fractal_server/app/api/v1/task.py
- tests/test_task_api.py
> Allow users to edit their own tasks

- CHANGELOG.md
- fractal_server/tasks/collection.py
- tests/test_task_collection_pypi.py
closes #740 
Relative pr for fractal-common: https://github.com/fractal-analytics-platform/fractal-common/pull/79
> Expose `pinned_package_versions` for task collection

- CHANGELOG.md
- fractal_server/app/api/v1/_aux_functions.py
- fractal_server/app/api/v1/task.py
- tests/test_task_api.py
- tests/test_unit_aux_functions.py
> Delete Task endpoint

- CHANGELOG.md
- README.md
- fractal_server/app/api/v1/task.py
- tests/test_task_api.py
> Expose `args_schema` and `args_schema_version` in task POST/PATCH

- CHANGELOG.md
- fractal_server/app/models/workflow.py
- fractal_server/app/runner/_local/_local_config.py
- fractal_server/app/runner/_slurm/_slurm_config.py
- tests/fixtures_tasks.py
- tests/test_unit_local_config.py
- tests/test_unit_slurm_config.py
- tests/test_workflow_api.py
> Remove `WorkflowTask.overridden_meta`

- CHANGELOG.md
- tests/test_unit_db_models.py
> Check SQL errors in the CI log

- fractal_server/app/models/task.py
- fractal_server/migrations/env.py
> Add render as batch to online method and add naming convention

- CHANGELOG.md
- fractal_server/app/runner/__init__.py
- tests/test_unit_submit_workflow.py
> Decorate failures in preliminary checks

- CHANGELOG.md
- fractal_server/app/api/v1/project.py
- tests/test_project_apply_api.py
> 791 prevent having two running jobs with the same output dataset

- CHANGELOG.md
- fractal_server/app/api/v1/task.py
- tests/test_task_api.py
> Accept `TaskUpdate.version=none`

- CHANGELOG.md
- fractal_server/config.py
- tests/data/example_server_startup/.gitignore
> Add `make_FRACTAL_TASKS_DIR_absolute` validator in `config.py`

- CHANGELOG.md
- fractal_server/app/models/job.py
> Fix status of `ApplyWorkflow.workflow_dump`

- CHANGELOG.md
- fractal_server/app/runner/_slurm/_slurm_config.py
> Replace `logger.error` with `logger.info` in SLURM-config function

- CHANGELOG.md
- fractal_server/app/api/v1/_aux_functions.py
- fractal_server/app/api/v1/workflow.py
- tests/test_workflow_api.py
> Add check in PATCH Workflow

- CHANGELOG.md
- fractal_server/app/api/v1/_aux_functions.py
- fractal_server/app/api/v1/project.py
> Add `_check_project_exists` helper function (closes #869)

- CHANGELOG.md
- fractal_server/app/runner/_common.py
- tests/data/non_python_task_issue878.sh
- tests/test_full_workflow.py
> Handle `null` in task metadiff JSON output

- .github/workflows/poetry_build.yml
- .github/workflows/publish_pypi.yml
- CHANGELOG.md
- docs/development.md
> Publish to pypi via dedicated GitHub action

- CHANGELOG.md
- fractal_server/app/api/v1/project.py
- fractal_server/app/schemas/project.py
- tests/test_dataset_api.py
- tests/test_job_api.py
- tests/test_project_api.py
- tests/test_project_apply_api.py
> Remove default Dataset from Project creation

- CHANGELOG.md
- fractal_server/config.py
- fractal_server/tasks/collection.py
- tests/fixtures_slurm.py
- tests/test_backend_runners.py
> Remove obsolete fixture `slurm_config`

- .github/workflows/ci.yml
- CHANGELOG.md
> Use ubuntu 22 in CI

- .github/workflows/ci.yml
- CHANGELOG.md
- tests/test_db.py
> Ruc CI both with sqlite and postgres

- CHANGELOG.md
- docs/internals/database_interface.md
- fractal_server/app/db/__init__.py
> Add information about minimal required sqlite version (close #910)

- CHANGELOG.md
- tests/fixtures_server.py
- tests/test_commands.py
> Make `test_commands` stateless with postgres

- .github/workflows/ci.yml
- CHANGELOG.md
> Disable postgres service when using sqlite in CI (ref #928)

- CHANGELOG.md
- fractal_server/migrations/script.py.mako
- poetry.lock
- pyproject.toml
> Remove `sqlalchemy_utils` dependency

- CHANGELOG.md
- fractal_server/app/schemas/json_schemas/manifest.json
- tests/test_unit_json_schemas.py
> 941 generate json schemas for some of the current appschemas pydantic models

- CHANGELOG.md
- fractal_server/app/api/v1/dataset.py
- tests/test_dataset_api.py
> Improve delete-resource endpoint

- CHANGELOG.md
- fractal_server/app/models/job.py
- fractal_server/app/models/state.py
- poetry.lock
- pyproject.toml
- tests/fixtures_server.py
> Update sqlmodel to 0.0.11

- CHANGELOG.md
- fractal_server/app/models/dataset.py
- tests/fixtures_server.py
- tests/test_dataset_api.py
> Add ID-based ordering for `Dataset.resource_list`

- CHANGELOG.md
- fractal_server/app/api/v1/project.py
- tests/fixtures_server.py
- tests/test_project_apply_api.py
> Fix construction of `ApplyWorkflow.workflow_dump` attribute

- CHANGELOG.md
- fractal_server/app/api/v1/job.py
- tests/test_job_api.py
> Change response of stop-job endpoint

- CHANGELOG.md
- tests/test_full_workflow.py
> Fix recursion error and remove `refresh` statements from `test_full_workflow.py` 

- CHANGELOG.md
> Update CHANGELOG for 1.3.14

- CHANGELOG.md
- fractal_server/app/routes/api/v1/dataset.py
- fractal_server/app/routes/api/v1/workflow.py
- tests/fixtures_server.py
- tests/test_dataset_api.py
- tests/test_workflow_api.py
>  Add endpoints to get all workflows/datasets of a given user

- CHANGELOG.md
- fractal_server/app/routes/api/v1/project.py
- fractal_server/app/schemas/applyworkflow.py
- tests/fixtures_server.py
- tests/test_unit_schemas.py
> Define types for `ApplyWorkflowRead` "dump" attributes, and fix their construction

- CHANGELOG.md
- fractal_server/app/routes/api/v1/dataset.py
- fractal_server/app/routes/api/v1/job.py
- fractal_server/app/routes/api/v1/workflow.py
- fractal_server/app/schemas/project.py
- tests/test_dataset_api.py
- tests/test_full_workflow.py
> Trim `ProjectRead` attributes and add `/project/{project_id}/dataset/` endpoint

- CHANGELOG.md
- fractal_server/app/routes/auth.py
- tests/test_security.py
> Remove delete-user endpoint

- CHANGELOG.md
- fractal_server/app/schemas/applyworkflow.py
> Relax response model constraints for dump attributes of `ApplyWorkflowRead`

- CHANGELOG.md
---
List of actual commits (which I pushed to `main` by mistake):
* [Add trailing slash to all endpoint paths (#1001) ](https://github.com/fractal-analytics-platform/fractal-server/commit/1cf7404ea5ad982869fd300d142177c0b7ca8502), 1cf7404ea5ad982869fd300d142177c0b7ca8502
* [Update path of /app/v1/{workflow,dataset,job}/ endpoints (ref #1001)](https://github.com/fractal-analytics-platform/fractal-server/commit/f158f786b442b69ac47f133f9abe4170c4693ffb), f158f786b442b69ac47f133f9abe4170c4693ffb
* [Update and fix test_background_tasks.py (close #1002) ](https://github.com/fractal-analytics-platform/fractal-server/commit/f0f671dd9c29839a0dd9ac55187d219022918c2b), f0f671dd9c29839a0dd9ac55187d219022918c2b
* [Update tests](https://github.com/fractal-analytics-platform/fractal-server/commit/afb0e2c …
> Dummy PR for endpoints update

- CHANGELOG.md
- fractal_server/app/routes/api/v1/_aux_functions.py
- fractal_server/app/routes/api/v1/task.py
> Remove `asyncio.gather`

- CHANGELOG.md
- fractal_server/main.py
> Skip creation of first-superuser when one superuser already exists

- CHANGELOG.md
- fractal_server/app/db/__init__.py
> add try except block also for sync session

- CHANGELOG.md
- fractal_server/app/routes/admin.py
- fractal_server/main.py
- tests/test_admin_api.py
> Move `/monitoring` endpoints to `/admin`

- CHANGELOG.md
- fractal_server/app/schemas/user.py
- tests/test_security.py
> Prevent user from updating their own password

- CHANGELOG.md
- fractal_server/app/routes/auth.py
- tests/test_security.py
closes #1026 
closes #1027 
closes #1028
closes #1029
> Clean up `fastapi_users` endpoint

- CHANGELOG.md
- poetry.lock
- pyproject.toml
> Yet another attempt at fixing CI

- .github/workflows/documentation.yaml
- CHANGELOG.md
> OAuth to Swagger

- CHANGELOG.md
- fractal_server/app/db/__init__.py
> Set `pool_pre_ping=True` for asyncpg-driven async DB engine

- .github/workflows/documentation.yaml
- CHANGELOG.md
> Add OAuth endpoints to swagger (ref #1025)

- .github/workflows/ci.yml
- .github/workflows/migrations.yml
- .github/workflows/poetry_build.yml
- .github/workflows/publish_pypi.yml
- CHANGELOG.md
- docs/development.md
> Use poetry 1.7

- CHANGELOG.md
- tests/fixtures_server.py
> Dispose of async engine in tests (close #1045)

- CHANGELOG.md
- fractal_server/app/runner/_slurm/executor.py
> Add `chdir` SLURM option, pointing to `job.working_dir_user`

- CHANGELOG.md
- fractal_server/app/schemas/task_collection.py
- tests/test_unit_schemas.py
closes #1039 
ref https://github.com/fractal-analytics-platform/fractal-web/issues/349
> Handle `.whl`+`version` in Task collection

- CHANGELOG.md
- fractal_server/main.py
> Make first-admin-user verified

- CHANGELOG.md
- fractal_server/app/routes/api/v1/task.py
- tests/api/test_project_apply_api.py
- tests/api/test_task_api.py
- tests/api/test_task_collection_api.py
- tests/api/test_workflow_api.py
> Prevent task creation to non-verified users

- CHANGELOG.md
- fractal_server/migrations/versions/efa89c30e0a4_add_project_timestamp_created.py
- scripts/fix_db/current.py
> Fix error in `scripts/fix_db/current.py`

- CHANGELOG.md
- fractal_server/app/runner/__init__.py
- fractal_server/app/runner/_local/__init__.py
- fractal_server/app/runner/_slurm/__init__.py
- fractal_server/app/runner/_slurm/_slurm_config.py
- fractal_server/app/runner/_slurm/executor.py
- tests/backend/test_backend_slurm.py
- tests/backend/test_unit_slurm_config.py
> 1076 use slurm account in slurm runner

- fractal_server/app/db/__init__.py
> Unify if-branches in `app.db.__init__.py`

- CHANGELOG.md
- fractal_server/app/routes/admin.py
- fractal_server/app/routes/api/v1/job.py
- tests/api/test_admin_api.py
- tests/api/test_job_api.py
> 1150 respond with 202 accepted for the two users and admins stop job endpoints

- CHANGELOG.md
- fractal_server/app/routes/api/v1/project.py
> Remove obsolete dependency from apply-workflow endpoint

- CHANGELOG.md
- fractal_server/app/runner/_slurm/executor.py
> Replace `#SBATCH --chdir=/path` with `#SBATCH -D /path`

- .github/workflows/migrations.yml
> Change order in `migrations` CI

- CHANGELOG.md
- fractal_server/app/schemas/user.py
- tests/schemas/test_unit_schemas.py
> Validate `UserCreate.slurm_accounts`

- CHANGELOG.md
- benchmarks/populate_db.py
- fractal_server/app/db/__init__.py
- fractal_server/app/routes/admin.py
- fractal_server/app/routes/api/v1/dataset.py
- fractal_server/app/routes/api/v1/job.py
- fractal_server/app/routes/api/v1/project.py
- fractal_server/app/routes/api/v1/task.py
- fractal_server/app/routes/api/v1/task_collection.py
- fractal_server/app/routes/api/v1/workflow.py
- fractal_server/app/routes/api/v1/workflowtask.py
- fractal_server/app/routes/auth.py
- fractal_server/app/security/__init__.py
- tests/04_api/test_background_tasks.py
- tests/fixtures_server.py
> Rename `DB.get_db` into `DB_get_async_db` (close #1181)

- .github/workflows/benchmarks.yaml
- .github/workflows/ci.yml
- .github/workflows/documentation.yaml
- .github/workflows/migrations.yml
- .github/workflows/poetry_build.yml
- .github/workflows/publish_pypi.yml
> Update actions/setup-python to v5

- .github/workflows/ci.yml
- .github/workflows/precommit.yml
> Extract precommit from CI action (close #1185)

- .github/workflows/ci.yml
- CHANGELOG.md
> Split tests in two groups

- benchmarks/templates/bench_diff_template.md
- docs/development.md
> Update release instructions

- docs/development.md
> Rewrite release instructions

- fractal_server/app/runner/__init__.py
> refactor error messages

- CHANGELOG.md
- fractal_server/app/routes/admin.py
- fractal_server/app/routes/api/v1/job.py
- fractal_server/app/routes/api/v1/task.py
- tests/04_api/test_admin_api.py
- tests/04_api/test_job_api.py
- tests/04_api/test_task_api.py
> 1217 trim response body of get tasks endpoint

- CHANGELOG.md
- benchmarks/api_bench.py
- fractal_server/app/routes/api/v1/dataset.py
- fractal_server/app/routes/api/v1/project.py
- fractal_server/app/schemas/dumps.py
- scripts/populate_db/populate_db_script.py
- tests/04_api/test_dataset_api.py
- tests/04_api/test_project_apply_api.py
> 1212 benchmark and optimize adminjob with large response

- CHANGELOG.md
- fractal_server/config.py
- fractal_server/main.py
> Remove CORS middleware

- CHANGELOG.md
- fractal_server/app/routes/admin.py
- fractal_server/app/routes/api/v1/job.py
- tests/04_api/test_admin_api.py
- tests/04_api/test_job_api.py
> Add `GET admin/job/{job_id}/`

- CHANGELOG.md
- fractal_server/app/routes/api/v1/project.py
> Fix error message

- CHANGELOG.md
- fractal_server/app/runner/_common.py
- fractal_server/app/runner/common.py
- fractal_server/config.py
- tests/01_unit/test_unit_runner_functions.py
> Remove image list from within `write_args_file`

- CHANGELOG.md
- fractal_server/app/runner/_slurm/_subprocess_run_as_user.py
- fractal_server/app/runner/_slurm/executor.py
- tests/05_backend/test_unit_custom_subprocess_module.py
- tests/08_full_workflow/test_full_workflow.py
- tests/data/tasks_dummy/dummy.py
> Fix wrong globbing filters within SLURM runner

- CHANGELOG.md
- fractal_server/app/db/__init__.py
- fractal_server/app/runner/__init__.py
- fractal_server/app/runner/_common.py
- fractal_server/app/runner/common.py
- tests/01_unit/test_unit_dummytasks.py
- tests/01_unit/test_unit_runner_functions.py
- tests/05_backend/test_backend_local.py
- tests/data/tasks_dummy/dummy.py
- tests/data/tasks_dummy/dummy_parallel.py
- tests/fixtures_slurm.py
- tests/fixtures_tasks.py
> Trim `TaskParameters` object before creating pickle files

- CHANGELOG.md
- fractal_server/app/runner/_common.py
- tests/01_unit/test_unit_runner_functions.py
> Also remove `history`, within `trim_TaskParameters`

- fractal_server/app/schemas/v2/dataset.py
- fractal_server/app/schemas/v2/dumps.py
- fractal_server/app/schemas/v2/workflowtask.py
- tests/v2/04_runner/test_fractal_demos_examples.py
- tests/v2/04_runner/test_full_workflows.py
- tests/v2/04_runner/test_unit_aux_functions.py
> import from subpackage

- .github/workflows/ci.yml
- CHANGELOG.md
- docs/development.md
- docs/install_and_deploy.md
- fractal_server/app/runner/__init__.py
- fractal_server/config.py
- poetry.lock
- pyproject.toml
- tests/data/slurm_docker_images/node/Dockerfile
> refactor _backends and add clusterfutures to required deps

- CHANGELOG.md
- fractal_server/app/routes/api/v1/dataset.py
- tests/04_api/test_history.py
> Handle `JSONDecodeError`

- fractal_server/app/runner/v2/runner.py
- fractal_server/app/runner/v2/runner_functions.py
- tests/v2/04_runner/fractal_tasks_core_mock/illumination_correction.py
- tests/v2/04_runner/fractal_tasks_core_mock/mip.py
- tests/v2/04_runner/fractal_tasks_core_mock/registration.py
- tests/v2/04_runner/test_fractal_tasks_core_examples.py
> Add `origin` to images

- fractal_server/app/models/v2/dataset.py
- fractal_server/app/routes/api/v2/__init__.py
- fractal_server/app/routes/api/v2/dataset.py
- fractal_server/app/routes/api/v2/images.py
- fractal_server/app/schemas/v2/dataset.py
- fractal_server/app/schemas/v2/dumps.py
- fractal_server/images/__init__.py
- fractal_server/migrations/versions/c6882af4aa97_v2.py
- tests/v2/01_schemas/test_unit_scalar_dict.py
- tests/v2/03_api/test_api_dataset.py
- tests/v2/03_api/test_api_dataset_images.py
> Images API v2

- fractal_server/app/routes/api/v2/images.py
> Images API

- CHANGELOG.md
- fractal_server/app/runner/_slurm/_check_jobs_status.py
- fractal_server/app/runner/_slurm/_executor_wait_thread.py
- tests/05_backend/test_backend_runners.py
- tests/05_backend/test_backend_slurm.py
- tests/05_backend/test_backend_slurm_shutdown.py
- tests/05_backend/test_unit_slurm_jobs_finished.py
- tests/08_full_workflow/test_full_workflow.py
- tests/fixtures_slurm.py
> 1249 make cfutslurmjobs finished more robust

- fractal_server/app/models/v2/dataset.py
- fractal_server/app/models/v2/task.py
- fractal_server/app/models/v2/workflowtask.py
- fractal_server/app/routes/api/v2/_aux_functions.py
- fractal_server/app/routes/api/v2/workflowtask.py
- fractal_server/app/schemas/v2/dataset.py
- fractal_server/app/schemas/v2/task.py
- fractal_server/app/schemas/v2/workflowtask.py
- fractal_server/migrations/versions/d57414993e22_v2.py
> Include new `SingleImage.flags` in API v2

- fractal_server/app/routes/api/v2/images.py
- fractal_server/images/__init__.py
- tests/v2/03_api/test_api_dataset_images.py
> New image query pagination

- fractal_server/app/routes/api/v2/images.py
- tests/v2/03_api/test_api_dataset_images.py
> Return last page if `page` is too big

- fractal_server/app/runner/v2/models.py
- fractal_server/app/runner/v2/runner.py
- fractal_server/app/runner/v2/runner_functions.py
- fractal_server/app/runner/v2/v1_compat.py
- tests/v2/04_runner/tasks_for_tests.py
- tests/v2/04_runner/test_apply_workflow.py
- tests/v2/04_runner/test_runner.py
> first try for v1 compatibility

- .github/workflows/ci_v1_selected.yml
- fractal_server/app/runner/v1/_common.py
- fractal_server/app/runner/v1/_local/_submit_setup.py
- fractal_server/app/runner/v1/_slurm/_submit_setup.py
> Simplify runner setup calls

- fractal_server/app/routes/api/v2/_aux_functions.py
- fractal_server/app/routes/api/v2/task.py
- fractal_server/app/schemas/v2/task.py
- tests/fixtures_server_v2.py
- tests/v2/03_api/test_api_task.py
> Test Task and WorkflowTask V2

- fractal_server/app/routes/api/v1/task.py
- fractal_server/app/routes/api/v2/task.py
- tests/v2/03_api/test_api_task.py
> Unique `source` for Task V1 and V2

- fractal_server/app/models/v2/task.py
> TaskV2 meta defaults

- fractal_server/app/routes/api/v2/images.py
- tests/v2/03_api/test_api_dataset_images.py
> Fix `page_size` in image pagination

- fractal_server/app/models/__init__.py
- fractal_server/app/models/v1/__init__.py
- fractal_server/app/routes/api/v1/job.py
- tests/v1/04_api/test_workflow_api.py
> 1329 do not re export app.schemas.v1 from app.models

- fractal_server/app/schemas/v2/dataset.py
- fractal_server/app/schemas/v2/job.py
- fractal_server/app/schemas/v2/project.py
- fractal_server/app/schemas/v2/task.py
- fractal_server/app/schemas/v2/workflow.py
- fractal_server/app/schemas/v2/workflowtask.py
- tests/v2/01_schemas/test_unit_schemas.py
> Always forbid extras in create pydantic models

- tests/v2/03_api/test_history.py
> Reintroduce dataset-status tests

- fractal_server/app/routes/admin/v2.py
- tests/v2/03_api/test_api_admin.py
> Re-enable get admin-v2 Project

- fractal_server/app/runner/v2/runner.py
> Fix obsolete `image.dict()` in runner

- tests/v1/04_api/test_project_apply_api.py
- tests/v2/03_api/test_api_submit_job.py
> Test rate limit

- fractal_server/app/routes/api/v2/_aux_functions.py
- fractal_server/app/routes/api/v2/dataset.py
- fractal_server/app/routes/api/v2/project.py
- fractal_server/app/routes/api/v2/workflow.py
- fractal_server/app/routes/api/v2/workflowtask.py
- tests/v2/03_api/test_api_dataset.py
- tests/v2/03_api/test_api_project.py
- tests/v2/03_api/test_api_workflow.py
> Use `flag_modified` and remove useless `db.commit`

- fractal_server/app/routes/api/v2/__init__.py
- fractal_server/app/routes/api/v2/_aux_functions.py
- fractal_server/app/routes/api/v2/submit.py
- fractal_server/app/schemas/v2/dumps.py
> Change submit-job API tag

- .github/workflows/benchmarks.yaml
- benchmarks/api_bench.py
- fractal_server/app/routes/api/v2/submit.py
- scripts/populate_db/fractal_client.py
- scripts/populate_db/populate_db_script.py
> Fix benchmarks GHA

- benchmarks/api_bench.py
- scripts/populate_db/fractal_client.py
> Exclude api/v1 from benchmark

- fractal_server/app/schemas/v2/workflowtask.py
- tests/v2/03_api/test_api_workflow.py
> Remove parallelisation_level validator from V2

- tests/v2/03_api/test_api_workflow.py
> Test PATCH workflow task

- fractal_server/app/routes/admin/v2.py
- fractal_server/app/schemas/v1/task.py
- tests/v1/02_schemas/test_unit_schemas.py
- tests/v2/03_api/test_api_admin.py
> `is_v2_compatible` as request body

- .github/workflows/benchmarks.yaml
> Fix benchmark GH action

- fractal_server/app/routes/api/v1/task_collection.py
- fractal_server/app/routes/api/v2/__init__.py
- fractal_server/app/routes/api/v2/task.py
- fractal_server/app/routes/api/v2/task_collection.py
- fractal_server/app/routes/api/v2/task_legacy.py
- fractal_server/app/schemas/v1/task.py
- fractal_server/app/schemas/v2/__init__.py
- fractal_server/app/schemas/v2/task.py
- tests/v1/04_api/test_task_collection_api.py
- tests/v2/03_api/test_api_task.py
- tests/v2/03_api/test_api_task_collection_failures.py
> Introduce endpoints/schemas for handling legacy tasks in V2

- fractal_server/app/models/v2/dataset.py
- fractal_server/app/models/v2/project.py
- fractal_server/app/routes/api/v2/submit.py
- fractal_server/app/schemas/v2/dataset.py
- fractal_server/app/schemas/v2/dumps.py
- fractal_server/app/schemas/v2/project.py
- fractal_server/app/schemas/v2/workflow.py
- fractal_server/migrations/versions/80e12e1bc4fd_v2.py
- tests/v2/03_api/test_api_dataset.py
- tests/v2/03_api/test_api_project.py
- tests/v2/03_api/test_api_submit_job.py
- tests/v2/08_full_workflow/test_full_workflow_v2.py
> Remove `read_only` from V2 projects and datasets (close #1384)

- fractal_server/app/routes/api/v2/dataset.py
- fractal_server/app/schemas/v2/dataset.py
- tests/v2/03_api/test_api_dataset.py
- tests/v2/03_api/test_api_dataset_images.py
> add import/export endpoints for dataset

- fractal_server/app/routes/api/v2/workflowtask.py
- fractal_server/app/runner/v2/_slurm/get_slurm_config.py
- fractal_server/app/runner/v2/handle_failed_job.py
- fractal_server/app/runner/v2/runner_functions_low_level.py
- tests/v2/03_api/test_api_workflow.py
- tests/v2/08_full_workflow/test_full_workflow_v2.py
Close #1405
Close #1390
Ref #1328
> Fixes related to using legacy tasks in V2 workflows

- fractal_server/app/runner/v2/runner.py
- tests/v2/04_runner/test_fractal_examples.py
> Improve log message

- benchmarks/api_bench.py
- benchmarks/templates/bench_diff_template.md
- fractal_server/app/schemas/v2/__init__.py
- scripts/populate_db/fractal_client.py
- scripts/populate_db/populate_db_script.py
> add image list to dataset in benchmarks

- .github/workflows/benchmarks.yaml
> Fix env variable in github action (close #1436)

- fractal_server/app/routes/api/v2/dataset.py
- fractal_server/app/schemas/v2/dataset.py
- tests/v2/01_schemas/test_schemas_dataset.py
- tests/v2/03_api/test_api_dataset.py
> Add cheks for dataset import

- CHANGELOG.md
- fractal_server/app/runner/executors/slurm/executor.py
- fractal_server/config.py
> Add `FRACTAL_SLURM_SBATCH_SLEEP` configuration variable (ref #1466)

- CHANGELOG.md
- tests/data/slurm_docker_images/docker-compose-private.yml
- tests/fixtures_slurm.py
- tests/v2/08_full_workflow/test_full_workflow_slurm_v2.py
> Make slurm CI work on MacOS

- CHANGELOG.md
- tests/data/slurm_docker_images/docker-compose-private.yml
- tests/data/slurm_docker_images/docker-compose.yml
- tests/data/slurm_docker_images/master/Dockerfile
- tests/data/slurm_docker_images/node/Dockerfile
This is needed (1) since I think I'm seeing tests being much slower than somewhere in the past (TBD), and (2) in view of containers which also offer SSH access.
> Review Docker images

- CHANGELOG.md
- tests/data/slurm_docker_images/node/Dockerfile
> Change order of dockerfile statements to improve caching

- CHANGELOG.md
- fractal_server/app/routes/api/v2/submit.py
- fractal_server/app/runner/v1/__init__.py
- fractal_server/config.py
- tests/no_version/test_unit_config.py
> Fix `cwd` related bug

- CHANGELOG.md
- tests/fixtures_slurm.py
> Set short timeout for `docker compose down`

- CHANGELOG.md
- fractal_server/app/runner/executors/slurm/executor.py
> Add `FractalSlurmExecutor.__exit__` method and stop/join thread

- CHANGELOG.md
- fractal_server/app/routes/api/v1/project.py
> Remove the catch of `IntegrityError` in `POST /api/v1/project`

- CHANGELOG.md
- fractal_server/app/routes/aux/_job.py
- fractal_server/app/runner/shutdown.py
- fractal_server/config.py
- fractal_server/main.py
- tests/fixtures_server.py
- tests/no_version/test_unit_lifespan.py
- tests/v2/03_api/test_submission_job_list_v2.py
> add shutdown logic in lifespan for executors

- tests/v2/03_api/test_api_admin.py
> Review behaviour of Admin-Task endpoint when a Project is deleted

- CHANGELOG.md
- fractal_server/app/runner/v2/__init__.py
- tests/v2/04_runner/test_background_task.py
> Handle errors in background tasks

- CHANGELOG.md
- fractal_server/app/runner/v1/__init__.py
- fractal_server/app/runner/v2/__init__.py
- fractal_server/app/runner/v2/_local_experimental/__init__.py
- fractal_server/app/runner/v2/_local_experimental/executor.py
- poetry.lock
- pyproject.toml
- tests/v1/01_unit/test_unit_submit_workflow.py
- tests/v2/04_runner/test_unit_submit_workflow.py
- tests/v2/09_backends/test_local_experimental.py
> Fix termination of processes in `FractalProcessPoolExecutor`

- CHANGELOG.md
- tests/v2/09_backends/test_local_experimental.py
> Test threads and processes with `local_experimental` backend

- fractal_server/app/routes/api/v2/task.py
- tests/v1/05_backend/test_backend_slurm.py
- tests/v1/05_backend/test_backend_slurm_shutdown.py
- tests/v2/03_api/test_api_admin.py
> Fix test warnings

- CHANGELOG.md
- fractal_server/app/routes/api/v2/task_collection_ssh.py
- fractal_server/app/runner/executors/slurm/ssh/executor.py
- fractal_server/ssh/_fabric.py
- fractal_server/tasks/v2/_venv_pip.py
- fractal_server/tasks/v2/background_operations.py
- fractal_server/tasks/v2/background_operations_ssh.py
- fractal_server/tasks/v2/endpoint_operations.py
- fractal_server/tasks/v2/utils.py
- tests/v2/06_tasks/test_tasks_v2_utils.py
> Improve SSH task collection

- CHANGELOG.md
- fractal_server/app/schemas/v2/task_collection.py
- fractal_server/tasks/v2/_TaskCollectPip.py
- fractal_server/tasks/v2/background_operations_ssh.py
- tests/v2/01_schemas/test_unit_schemas_v2.py
- tests/v2/06_tasks/test_TaskCollectPip_model.py
> Task-collection fixes

- CHANGELOG.md
- fractal_server/app/schemas/v2/task_collection.py
> Minor fix in `TaskCollectCustomV2` validator

- CHANGELOG.md
- fractal_server/app/routes/api/v2/task_collection_custom.py
- fractal_server/app/schemas/v2/task_collection.py
- tests/v2/01_schemas/test_task_collection.py
- tests/v2/03_api/test_api_task_collection.py
closes #1616 
closes #1615 
closes #1612
> Improve task-collection endpoint

- CHANGELOG.md
- fractal_server/app/routes/api/v2/task_collection_custom.py
- tests/v2/03_api/test_api_task_collection.py
ref #1581 
ref https://github.com/fractal-analytics-platform/fractal-web/pull/523#issuecomment-2217706992
> Check for file existence in custom task collection

- CHANGELOG.md
- fractal_server/ssh/_fabric.py
- tests/v2/00_ssh/test_FractalSSH.py
> Remove `FractalSSH.rename_folder` method

- CHANGELOG.md
- fractal_server/config.py
> Make `FRACTAL_SLURM_SBATCH_SLEEP` config variable `float`

- CHANGELOG.md
- fractal_server/app/routes/api/__init__.py
- fractal_server/config.py
- tests/no_version/test_alive.py
> New `/settings/` endpoint

- CHANGELOG.md
- fractal_server/app/routes/api/v1/project.py
- fractal_server/config.py
- fractal_server/main.py
- tests/v1/04_api/test_project_apply_api.py
> New option "include_without_submission" for `FRACTAL_API_V1_MODE`

- .github/workflows/ci.yml
- CHANGELOG.md
- tests/v1/04_api/test_admin_api.py
- tests/v2/03_api/test_api_admin.py
> Test python3.11

- CHANGELOG.md
- tests/fixtures_docker.py
- tests/fixtures_server.py
- tests/fixtures_slurm.py
- tests/fixtures_tasks_v1.py
- tests/fixtures_tasks_v2.py
> Remove `HAS_LOCAL_SBATCH` check

- CHANGELOG.md
- benchmarks/api_bench.py
> Add `current-user` endpoint to benchmarks

- CHANGELOG.md
- docs/doc-requirements.txt
- poetry.lock
- pyproject.toml
> Fix `Test docs build` broken gha

- CHANGELOG.md
- fractal_server/zip_tools.py
> Add logging to `zip_tools`

- .github/workflows/ci.yml
- CHANGELOG.md
- benchmarks/api_bench.py
> Add login endpoint to benchmarks

- CHANGELOG.md
- fractal_server/app/runner/v2/__init__.py
- fractal_server/app/runner/v2/_slurm_ssh/__init__.py
- tests/v2/08_full_workflow/common_functions.py
- tests/v2/08_full_workflow/test_full_workflow_slurm_ssh_v2.py
> Move SSH remote-folder creation to `_process_workkflow` (ref #1727)

- CHANGELOG.md
- fractal_server/app/security/__init__.py
> Drop try/except for IntegrityError in first-user creation

- CHANGELOG.md
- scripts/validate_db_data_with_read_schemas.py
> Add user groups validation to `validate_db_data_with_read_schemas.py`

- CHANGELOG.md
- fractal_server/app/routes/auth/group.py
- fractal_server/app/routes/auth/users.py
- fractal_server/app/schemas/user.py
- fractal_server/app/schemas/user_group.py
- tests/no_version/test_auth_api.py
- tests/no_version/test_auth_groups_api.py
> Handle more edge cases in user/group API

- CHANGELOG.md
- fractal_server/app/routes/auth/users.py
- tests/no_version/test_auth_api.py
> Re-add check of existing-user in `PATCH /auth/users/{id}/`

- fractal_server/app/schemas/user.py
> Add `oauth_accounts` to `UserRead`

- fractal_server/app/runner/executors/slurm/ssh/executor.py
- fractal_server/app/runner/executors/slurm/sudo/executor.py
- fractal_server/ssh/_fabric.py
- tests/conftest.py
- tests/no_version/test_backend_slurm.py
> Fix spurious threads in tests and Slurm executor

- fractal_server/app/routes/api/v1/project.py
- fractal_server/app/routes/api/v2/submit.py
- fractal_server/app/routes/aux/validate_user_settings.py
- tests/v1/04_api/test_project_apply_api.py
- tests/v1/07_full_workflow/test_full_workflow.py
- tests/v2/03_api/test_api_job.py
> Propagate settings to job-execution background task

- fractal_server/app/models/user_settings.py
- fractal_server/app/routes/auth/current_user.py
- fractal_server/app/routes/auth/users.py
- fractal_server/app/routes/aux/validate_user_settings.py
- fractal_server/app/user_settings.py
- tests/no_version/test_unit_user_settings.py
> Alwasy call `verify_user_has_settings` before `db.get(UserSettings, user.user_settings_id`)

- CHANGELOG.md
- fractal_server/app/schemas/user_settings.py
- tests/no_version/test_unit_schemas_no_version.py
> Add missing `UserSettingsReadStrict.ssh_username`

- CHANGELOG.md
- fractal_server/app/schemas/v2/task_collection.py
- fractal_server/ssh/_fabric.py
- fractal_server/string_tools.py
- tests/v2/00_ssh/test_FractalSSH.py
- tests/v2/01_schemas/test_task_collection.py
> Remove redundant command-string validations

- CHANGELOG.md
- fractal_server/app/runner/executors/slurm/ssh/executor.py
- fractal_server/app/runner/executors/slurm/sudo/executor.py
> Minor improvements to SSH/sudo SLURM executors

- .github/workflows/migrations.yml
- CHANGELOG.md
- fractal_server/migrations/env.py
- tests/data/testing_databases/.fractal_server_postgres.env
> Fix naming convention and test db downgrade

- tests/v2/03_api/test_loss_of_access_to_task.py
> Test loss-of-access-to-task scenario

- CHANGELOG.md
- fractal_server/tasks/v2/endpoint_operations.py
- tests/v2/06_tasks/test_get_package_version_from_pypi.py
> Discover latest version of task package from pypi / auxiliary function

- CHANGELOG.md
- fractal_server/app/routes/api/v2/workflow.py
ref https://github.com/fractal-analytics-platform/fractal-web/issues/578#issuecomment-2401685821
> Add warnings to `PATCH /api/v2/project/{id}/workflow/{id}/` return model

- CHANGELOG.md
- fractal_server/app/routes/api/v2/workflow.py
- tests/v2/03_api/test_api_workflow.py
ref #1868 
ref https://github.com/fractal-analytics-platform/fractal-web/issues/578#issuecomment-2401685821
> Populate warnings in `PATCH /api/v2/project/{id}/workflow/{id}/`

- .github/workflows/ci.yml
> Move V1 CI to new postgres adapter

- fractal_server/__main__.py
- fractal_server/data_migrations/2_7_0.py
> Deprecate `update-db-data --dry-run` option

- CHANGELOG.md
- fractal_server/app/schemas/v2/task_collection.py
- tests/v2/03_api/test_api_task_collection.py
- tests/v2/03_api/test_api_task_collection_ssh.py
> Test validation of task collection payload

- CHANGELOG.md
- fractal_server/app/routes/api/v2/task_collection_custom.py
- fractal_server/app/schemas/v2/task_collection.py
- fractal_server/tasks/v1/_TaskCollectPip.py
- tests/v2/01_schemas/test_task_collection.py
- tests/v2/03_api/test_api_task_collection.py
- tests/v2/03_api/test_api_task_collection_custom.py
> Rename custom-task-collection `source` into `label`

- CHANGELOG.md
- fractal_server/app/routes/api/v1/task_collection.py
- fractal_server/app/routes/api/v2/task_collection.py
- fractal_server/tasks/utils.py
- fractal_server/tasks/v1/background_operations.py
- fractal_server/tasks/v1/get_collection_data.py
- fractal_server/tasks/v2/background_operations.py
- fractal_server/tasks/v2/endpoint_operations.py
- tests/no_version/test_unit_tasks_no_version.py
- tests/v2/03_api/test_api_task_collection.py
- tests/v2/03_api/test_api_task_collection_ssh.py
- tests/v2/06_tasks/test_endpoint_operations_v2.py
- tests/v2/06_tasks/test_tasks_v2_utils.py
Close #1897
Close #1898
Close #1899
> Improve task-collection endpoint and response

- CHANGELOG.md
- fractal_server/app/routes/api/v2/_aux_functions.py
- fractal_server/app/routes/api/v2/workflowtask.py
- fractal_server/app/schemas/v2/workflowtask.py
- tests/v2/03_api/test_api_workflow_task.py
> Drop `WorkflowTaskCreateV2.order`

- CHANGELOG.md
- fractal_server/app/schemas/v2/task.py
- tests/v2/03_api/test_api_task.py
> Drop `TaskUpdateV2.version`

- CHANGELOG.md
- fractal_server/app/routes/admin/v2/task.py
- fractal_server/app/schemas/v2/dumps.py
- fractal_server/app/schemas/v2/task.py
- scripts/client/client.py
- tests/v2/01_schemas/test_unit_schemas_v2.py
- tests/v2/03_api/test_api_admin.py
- tests/v2/03_api/test_api_workflow_task.py
> Reduce use of `owner` and `source`

- CHANGELOG.md
- fractal_server/app/routes/api/v2/task_collection.py
- fractal_server/app/routes/api/v2/task_group.py
- tests/v2/03_api/test_api_task_group.py
> Fix patch task group

- CHANGELOG.md
- benchmarks/api_bench.py
> Benchmark `GET /api/v2/task-group/`

- CHANGELOG.md
- fractal_server/app/runner/v2/__init__.py
> Only use 755 permissions for job folder if using SLURM/sudo

- CHANGELOG.md
- fractal_server/data_migrations/2_7_0.py
> Normalize `pkg_name` in data-migration script

- CHANGELOG.md
- fractal_server/app/routes/api/v2/workflow_import.py
- tests/data/import_export/workflow-v2.json
- tests/v2/03_api/test_api_workflow_import_export.py
> Fix import-workflow

- CHANGELOG.md
- fractal_server/app/routes/api/v2/_aux_functions_tasks.py
- fractal_server/app/routes/api/v2/task_group.py
- tests/v2/03_api/test_api_task_group.py
> Optionally exclude JSON schemas from `GET task-group`

- CHANGELOG.md
- fractal_server/app/routes/api/v2/submit.py
- tests/v2/03_api/test_api_job.py
> Remove rate limit for submit-job v2 endpoint

- CHANGELOG.md
- fractal_server/app/routes/api/v2/workflow_import.py
> Use kwargs when calling `_disambiguate_task_groups`

- CHANGELOG.md
- fractal_server/app/runner/executors/slurm/ssh/executor.py
- tests/v2/00_ssh/test_executor.py
>  Make sure that the whole FractalSSHSlurmExecutor._completion method is whitin a try/except block #1962 

- .github/workflows/migrations.yml
- CHANGELOG.md
> Do install setuptools in migrations.yml

- CHANGELOG.md
- fractal_server/app/routes/admin/v2/task_group.py
- fractal_server/app/routes/api/v2/task.py
- fractal_server/app/routes/api/v2/task_collection.py
- fractal_server/app/routes/api/v2/task_collection_custom.py
- fractal_server/app/schemas/v2/__init__.py
- fractal_server/app/schemas/v2/task_group.py
- tests/fixtures_server_v2.py
- tests/v2/03_api/test_api_admin.py
> Add query parameters in admin get-task-group endpoint

- fractal_server/app/runner/executors/slurm/_slurm_config.py
- fractal_server/app/schemas/_filter_validators.py
- tests/v2/01_schemas/test_schemas_dataset.py
> Handle the fact that `bool` is a subset of `int`

- fractal_server/app/routes/api/v2/dataset.py
- fractal_server/app/routes/api/v2/workflow.py
- fractal_server/app/routes/api/v2/workflowtask.py
- tests/v2/test_09_history/test_history_api.py
> Cascade delete for image status

- fractal_server/app/models/v2/history.py
- fractal_server/app/routes/api/v2/_aux_functions.py
- fractal_server/app/routes/api/v2/history.py
- fractal_server/migrations/versions/954ddc64425a_image_status.py
- tests/v2/test_09_history/test_history_api.py
> Update and expose `ImageStatus.logfile`

- CHANGELOG.md
- fractal_server/app/routes/api/v2/job.py
- tests/v2/test_03_api/test_api_job.py
> New latest-job endpoint

- fractal_server/app/routes/api/v2/history.py
- tests/v2/test_07_full_workflow/common_functions.py
- tests/v2/test_09_history/test_history_api.py
> Improve access control for History API

- docs/install_and_deploy.md
There is a broken link on install page that i think could be fixed like that. 
Best.
> Update install_and_deploy link do developement page

- CHANGELOG.md
- tests/v2/test_00_ssh/test_FractalSSH.py
> Make `test_FractalSSH.py::test_folder_utils` work on MacOS

- CHANGELOG.md
- fractal_server/tasks/v2/local/collect_pixi.py
- fractal_server/tasks/v2/local/reactivate_pixi.py
- fractal_server/tasks/v2/ssh/collect_pixi.py
- fractal_server/tasks/v2/ssh/reactivate_pixi.py
- pyproject.toml
- tests/v2/test_00_ssh/test_FractalSSHList.py
- tests/v2/test_06_tasks_lifecycle/test_api_task_lifecycle_pixi_ssh.py
- tests/v2/test_07_full_workflow/test_full_workflow_slurm_sudo.py
> Update `chmod -R` and add pytest marker `fails_on_macos`

- CHANGELOG.md
- fractal_server/app/routes/admin/v2/job.py
- tests/v2/test_03_api/admin/test_admin_job.py
> Improve logging for `PATCH /admin/v2/job/{job_id}/`

- CHANGELOG.md
- fractal_server/app/routes/admin/v2/job.py
- tests/v2/test_03_api/admin/test_admin_job.py
> Update workflow status numbers when workflow manually gets labeled as failed

- CHANGELOG.md
- fractal_server/app/runner/executors/slurm_ssh/runner.py
- fractal_server/ssh/_fabric.py
- tests/v2/test_00_ssh/test_FractalSSH.py
- tests/v2/test_08_backends/test_slurm_ssh_squeue.py
> handling socket errors with retry
