fractal-analytics-platform/fractal-server

.github/workflows/ci.yml

Remove python 3.9 from github CI [closes #37]

---

.github/workflows/ci.yml

closes https://github.com/fractal-analytics-platform/fractal-server/issues/57
(also using poetry 1.2.1 in CI)

Fix `Command not found: pytest` in CI (and use poetry 1.2.1) [closes #57]

---

.gitignore
fractal_server/app/runner/__init__.py
fractal_server/app/runner/runner_utils.py
fractal_server/config.py
poetry.lock
tests/test_apply_worfklow.py

Per-workflow logging

---

fractal_server/config.py
fractal_server/tasks/collection.py
tests/test_task_collection_pypi.py
tests/test_unit_settings.py

@tcompa fractal-analytics-platform/fractal#326 might be a client error that does not send the version number to the server. Unit tests added by this PR behave as expected.

240 include version in tasks package directory server or client issue

---

fractal_server/tasks/collection.py
tests/fixtures_server.py
tests/test_full_workflow.py
tests/test_task_api.py
tests/test_task_collection_pypi.py

* set automatically database engine in tests by looking for `asyncpg`  (i.e., if you want to automatically run on `sqlite` simply do not `poetry install` the `postgres` extra)
Close #251

294 test collection of python38 tasks when server is run on python 38

---

fractal_server/app/runner/__init__.py
tests/data/slurm_config.json
tests/fixtures_server.py
tests/fixtures_tasks.py
tests/test_fixtures_settings_factory.py
tests/test_full_workflow.py

this makes it easier for testing, but might make configuration error discovery slower for deployment as the system would only fail at the first use of the backend instead of at startup

delay backend selection

---

.github/workflows/ci.yml
fractal_server/__main__.py
fractal_server/alembic.ini
pyproject.toml

Introduce a single entrypoint `fractalctl` (`__main__` of the package) which allows to
* run the server
* save the openapi schema
* run the database migration
Close #357

setup database from `fractalctl`

---

tests/conftest.py

This removes a warning from pytest

Register pytest slow marker

---

tests/fixtures_server.py
tests/test_security.py

requires: #403 
closes #433 
ref #442
Possible simplification

Test all relevant `/users` routers

---

poetry.lock
pyproject.toml
tests/data/slurm_docker_images/node/Dockerfile
tests/fixtures_slurm.py
tests/test_backend_runners.py
tests/test_backend_slurm.py

Refs:
* #479
* #481
We found a major issue in the CI (thanks @ychiucco!), i.e. fractal-server install in docker container was pulling the fresh sqlalchemy 2.0 version (released yesterday), which introduces major changes and is not (yet) supported by our dependencies.
This is currently addressed by pinning to >=1.4,<2, and we should also come back to this later if a PR like https://github.com/fastapi-users/fastapi-users-db-sqlmodel/pull/13 is merged (I think this is the dependency which is currently holding us back at 1.4.35), to make sure that we would fetch more recent 1.4 versions if possible.
Meanwhile, another small issue (`cfut_finished_jobs` fixture missing in some tests, and its actual code being slightly different from the cfut=0.5 final version) surfaced, and is fixed here.

Attempts to fix CI

---

CHANGELOG.md
docs/internals/runners/index.md
docs/internals/runners/local.md
docs/internals/runners/slurm.md
fractal_server/app/runner/_common.py
fractal_server/app/runner/_local/__init__.py
fractal_server/app/runner/_local/_local_config.py
fractal_server/app/runner/_local/_submit_setup.py
fractal_server/app/runner/_local/executor.py
fractal_server/config.py
tests/test_backend_local.py
tests/test_unit_fractal_thread_pool_executor.py
tests/test_unit_local_config.py
tests/test_unit_settings.py

Update `local` backend

---

CHANGELOG.md
fractal_server/app/api/v1/project.py
tests/test_full_workflow.py
tests/test_project_api.py

workflow-apply error handling

---

CHANGELOG.md
fractal_server/app/models/workflow.py
fractal_server/app/runner/_common.py
tests/fixtures_tasks.py
tests/test_backend_local.py
tests/test_unit_slurm_config.py

1. Drop `WorkflowTask.arguments` property, and use `wftask.args or {}` when needed.
2. Drop `WorkflowTask.assemble_args` method, and set arguments of `write_args_file` correctly.
3. Improve docstrings.

Drop `WorkflowTask.arguments` property (close #741)

---

CHANGELOG.md
fractal_server/app/models/workflow.py
tests/test_unit_db_models.py

Fix bug in task insertion when `task.meta=None`

---

CHANGELOG.md
poetry.lock
pyproject.toml
tests/fixtures_slurm.py

Fix pyyaml and docker-compose dependencies

---

CHANGELOG.md
fractal_server/app/runner/_slurm/_executor_wait_thread.py
fractal_server/app/runner/_slurm/_slurm_config.py
fractal_server/app/runner/_slurm/_subprocess_run_as_user.py
fractal_server/app/runner/_slurm/executor.py
fractal_server/config.py
tests/fixtures_server.py

(ref #884)
PRELIMINARY: With this change, the check of whether a job is complete (or failed) is fully deferred to the `jobs_finished` function (which only calls `squeue`, and then does not require `sudo`). We still rely on file-existence check to detect a shutdown event, but this does not require sudo.

Review checks for completed jobs in `FractalFileWaitThread.check`

---

CHANGELOG.md
fractal_server/app/runner/_common.py
tests/test_full_workflow.py

Fix parallel-task metadata aggregation for SLURM backend

---

CHANGELOG.md
fractal_server/app/api/v1/dataset.py
fractal_server/app/api/v1/project.py
fractal_server/app/models/job.py
fractal_server/app/runner/__init__.py
fractal_server/app/schemas/__init__.py
fractal_server/app/schemas/applyworkflow.py
tests/test_unit_submit_workflow.py

Review use of `Enum`s

---

CHANGELOG.md
fractal_server/app/routes/monitoring.py
tests/test_monitoring.py

Add `user_id` as monitoring query parameter

---

fractal_server/config.py

OAUTH env variables must starts with `OAUTH_`

---

CHANGELOG.md
fractal_server/app/models/dataset.py
fractal_server/app/models/project.py
fractal_server/app/models/workflow.py
fractal_server/app/routes/api/v1/job.py
fractal_server/app/routes/api/v1/project.py
tests/fixtures_server.py
tests/test_full_workflow.py
tests/test_project_api.py
tests/test_unit_db_models.py

By removing three nested relationships from `Project`, we hugely improve the performance bottleneck described in https://github.com/fractal-analytics-platform/fractal-web/issues/361.

Reduce project relationships

---

CHANGELOG.md
fractal_server/logger.py
fractal_server/logger/__init__.py
fractal_server/logger/gunicorn_logger.py
fractal_server/main.py
tests/data/example_server_startup/.gitignore
tests/data/example_server_startup/cleanup.sh
tests/data/example_server_startup/run_server.sh
tests/data/example_server_startup/run_server_gunicorn.sh
tests/data/example_server_startup/run_server_uvicorn.sh
tests/no_version/test_unit_config_uvicorn_loggers.py

Improve uvicorn/gunicorn logging

---

fractal_server/app/routes/api/v2/_aux_functions.py
tests/v2/03_api/test_unit_aux_functions.py
tests/v2/04_runner/test_unit_aux_functions_v2.py

Review use of `db.refresh` in aux functions

---

CHANGELOG.md
fractal_server/ssh/_fabric.py
fractal_server/tasks/v2/background_operations_ssh.py
fractal_server/tasks/v2/templates/_1_create_venv.sh
fractal_server/tasks/v2/templates/_2_upgrade_pip.sh
fractal_server/tasks/v2/templates/_3_pip_install.sh
fractal_server/tasks/v2/templates/_4_pip_freeze.sh
fractal_server/tasks/v2/templates/_5_pip_show.sh
tests/v2/00_ssh/test_FractalSSH.py
tests/v2/00_ssh/test_task_collection_ssh.py

Fix SSH task collection folder removal upon failure

---

.github/workflows/ci.yml
CHANGELOG.md

Do not test V1 with psycopg

---

CHANGELOG.md
fractal_server/app/runner/executors/slurm/ssh/_executor_wait_thread.py
fractal_server/app/runner/executors/slurm/ssh/executor.py
tests/v2/00_ssh/test_executor.py

Handle early shutdown in SSH executor

---

tests/v2/01_schemas/test_schemas_workflow.py
tests/v2/01_schemas/test_task_collection.py
tests/v2/01_schemas/test_unit_schemas_v2.py

Coverage schemas 100%

---

CHANGELOG.md
poetry.lock
pyproject.toml

Bump FastAPI version

---

CHANGELOG.md
fractal_server/zip_tools.py

Fix logging in ziptools

---

.github/workflows/ci.yml
CHANGELOG.md

Update artifact GitHub Actions

---

fractal_server/app/models/user_settings.py
fractal_server/app/routes/api/v2/_aux_functions.py
fractal_server/app/routes/api/v2/submit.py
fractal_server/app/routes/api/v2/task_collection.py
fractal_server/app/routes/aux/validate_user_settings.py
fractal_server/user_settings.py
tests/fixtures_server.py
tests/no_version/test_unit_user_settings.py
tests/v2/03_api/test_api_task_collection_ssh.py
tests/v2/08_full_workflow/common_functions.py
tests/v2/08_full_workflow/test_full_workflow_slurm_ssh_v2.py

Validate SSH user settings in API

---

CHANGELOG.md
fractal_server/app/schemas/v2/dumps.py
tests/v2/03_api/test_unit_issue_1783.py

Fix v2.5.0 bug in DatasetRead response validation

---

fractal_server/app/routes/aux/validate_user_settings.py
fractal_server/user_settings.py
tests/no_version/test_unit_user_settings.py
tests/v2/03_api/test_api_job.py
tests/v2/08_full_workflow/common_functions.py
tests/v2/08_full_workflow/test_full_workflow_slurm_v2.py

Validate sudo-slurm user settings

---

fractal_server/app/schemas/user.py
tests/no_version/test_auth_api.py
tests/no_version/test_unit_schemas_no_version.py

Remove legacy attributes from `UserUpdate/Read` schemas

---

docs/development.md
fractal_server/app/routes/api/v2/submit.py
fractal_server/app/routes/api/v2/task_collection.py
fractal_server/app/runner/v2/__init__.py
fractal_server/config.py
fractal_server/tasks/v2/background_operations_ssh.py
tests/no_version/test_unit_lifespan.py
tests/v2/00_ssh/test_task_collection_ssh.py
tests/v2/03_api/test_api_task_collection_ssh.py
tests/v2/04_runner/test_background_task.py
tests/v2/04_runner/test_unit_submit_workflow.py
tests/v2/08_full_workflow/test_full_workflow_slurm_ssh_v2.py

Propagate user's settings into SSH background tasks

---

CHANGELOG.md
fractal_server/app/schemas/_validators.py
fractal_server/app/schemas/user_settings.py
tests/no_version/test_unit_schemas_no_version.py

Allow setting `UserSettings` nullable attributes to `None` in PATCH endpoints

---

CHANGELOG.md
fractal_server/app/routes/auth/group.py
tests/no_version/test_api_user_groups.py

Introduce PATCH user settings bulk-endpoint for user group

---

CHANGELOG.md
fractal_server/app/routes/api/v2/_aux_functions.py
fractal_server/app/routes/api/v2/_aux_functions_tasks.py
fractal_server/app/routes/api/v2/images.py
fractal_server/app/routes/api/v2/submit.py
fractal_server/app/routes/api/v2/workflow_import.py
fractal_server/app/routes/api/v2/workflowtask.py
fractal_server/app/runner/executors/slurm/ssh/executor.py
tests/v2/03_api/test_api_job.py
tests/v2/03_api/test_api_workflow_import_export.py
tests/v2/03_api/test_api_workflow_task.py

Verify compatibility between `WorkflowTaskV2.type_filters` and `TaskV2.input_types`

---

fractal_server/config.py

Drop `FRACTAL_RUNNER_TASKS_INCLUDE_IMAGE`
